# Generated by Django 2.2.4 on 2019-09-19 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_auto_20190919_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 9, 19, 3, 52, 28, 386858)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 9, 19, 3, 52, 28, 386858)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='prioridad',
            field=models.CharField(choices=[('LEVE', 'LEVE'), ('MODERADO', 'MODERADO'), ('URGENTE', 'URGENTE')], default='LEVE', max_length=10),
        ),
    ]
