# Generated by Django 2.2.4 on 2019-09-23 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_auto_20190919_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='otros',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 9, 22, 23, 34, 57, 356478)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 9, 22, 23, 34, 57, 356478)),
        ),
    ]
