# Generated by Django 2.2.4 on 2019-09-23 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_auto_20190922_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 9, 23, 0, 24, 27, 993817)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 9, 23, 0, 24, 27, 993817)),
        ),
    ]
