# Generated by Django 3.0.2 on 2020-01-15 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_auto_20190923_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 1, 15, 13, 10, 49, 895629)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2020, 1, 15, 13, 10, 49, 895611)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='prioridad',
            field=models.CharField(choices=[('LEVE', 'LEVE'), ('MODERADO', 'MODERADO'), ('URGENTE', 'URGENTE')], default='LEVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo_beneficiario',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('BENFICIARIO', 'BENFICIARIO'), ('RENTISTA', 'RENTISTA')], default='ACTIVO', max_length=20),
        ),
    ]
